"""empty message

Revision ID: 2393e578c9d1
Revises: 
Create Date: 2024-01-11 18:50:01.417682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2393e578c9d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_name'), ['name'], unique=True)

    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('is_subfoder', sa.Boolean(), nullable=True),
    sa.Column('paren_folder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folder_name'), ['name'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pic_addr', sa.String(length=250), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_id'))

    op.drop_table('note')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_name'))
        batch_op.drop_index(batch_op.f('ix_folder_id'))

    op.drop_table('folder')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_name'))
        batch_op.drop_index(batch_op.f('ix_subject_id'))

    op.drop_table('subject')
    # ### end Alembic commands ###
