"""empty message

Revision ID: 346220b7be5a
Revises: e2a2553d7ef0
Create Date: 2024-01-11 19:01:28.191588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346220b7be5a'
down_revision = 'e2a2553d7ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_root', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_column('is_root')

    # ### end Alembic commands ###
