"""empty message

Revision ID: 499882025a5e
Revises: 346220b7be5a
Create Date: 2024-01-11 22:40:17.175498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499882025a5e'
down_revision = '346220b7be5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subfolder', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_subfoder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subfoder', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_subfolder')

    # ### end Alembic commands ###
