"""empty message

Revision ID: e2a2553d7ef0
Revises: 2393e578c9d1
Create Date: 2024-01-11 18:51:12.052138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a2553d7ef0'
down_revision = '2393e578c9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_folder', sa.Integer(), nullable=True))
        batch_op.drop_column('paren_folder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paren_folder', sa.INTEGER(), nullable=True))
        batch_op.drop_column('parent_folder')

    # ### end Alembic commands ###
